import argparse
import json
import os
from datetime import datetime, timedelta, timezone
from statistics import mean


AGENT_WORKFLOWS = {
    "Quinn (QA Engineer)": ".github/workflows/qa-engineer.yml",
    "Morgan (Project Manager)": ".github/workflows/project-manager.yml",
    "Alex (Product Owner)": ".github/workflows/product-owner.yml",
    "Casey (Council Moderator)": ".github/workflows/council-discussion.yml",
}


def parse_ts(raw):
    return datetime.fromisoformat(raw.replace("Z", "+00:00"))


def collect_metrics(runs, since, agent_workflows=None):
    workflows = agent_workflows or AGENT_WORKFLOWS
    metrics = {
        agent: {"runs": 0, "failures": 0, "durations": [], "last_run": None}
        for agent in workflows
    }

    for run in runs:
        path = run.get("path") or ""
        created_raw = run.get("created_at")
        updated_raw = run.get("updated_at")
        status = run.get("status")
        conclusion = run.get("conclusion")

        if not created_raw:
            continue
        created_at = parse_ts(created_raw)
        if created_at < since:
            continue

        matched_agent = None
        for agent, workflow_path in workflows.items():
            if path.endswith(workflow_path):
                matched_agent = agent
                break
        if not matched_agent:
            continue

        data = metrics[matched_agent]
        data["runs"] += 1
        if data["last_run"] is None or created_at > data["last_run"]:
            data["last_run"] = created_at
        if status == "completed" and conclusion and conclusion != "success":
            data["failures"] += 1
        if status == "completed" and updated_raw:
            updated_at = parse_ts(updated_raw)
            duration_minutes = max((updated_at - created_at).total_seconds() / 60.0, 0.0)
            data["durations"].append(duration_minutes)

    return metrics


def build_rows(metrics):
    rows = []
    for agent, data in metrics.items():
        total = data["runs"]
        failures = data["failures"]
        successes = max(total - failures, 0)
        success_rate = (successes / total * 100.0) if total else 0.0
        avg_duration = mean(data["durations"]) if data["durations"] else 0.0
        last_dt = data["last_run"]
        rows.append(
            {
                "agent": agent,
                "runs": total,
                "failures": failures,
                "success_rate": success_rate,
                "avg_duration": avg_duration,
                "last_run": last_dt.strftime("%Y-%m-%d") if last_dt else "No runs",
                "last_run_sort": last_dt or datetime(1970, 1, 1, tzinfo=timezone.utc),
            }
        )
    return rows


def sort_rows(rows, sort_by):
    if sort_by == "runs":
        rows.sort(key=lambda r: r["runs"], reverse=True)
    elif sort_by == "failures":
        rows.sort(key=lambda r: r["failures"], reverse=True)
    elif sort_by == "avg-duration":
        rows.sort(key=lambda r: r["avg_duration"], reverse=True)
    elif sort_by == "last-run":
        rows.sort(key=lambda r: r["last_run_sort"], reverse=True)
    else:
        rows.sort(key=lambda r: r["success_rate"], reverse=True)
    return rows


def render_markdown(rows, current_date, period_days, sort_by, workflow_url):
    kpi_lines = "\n".join(
        f"| {r['agent']} | {r['runs']} | {r['success_rate']:.1f}% | {r['failures']} | {r['avg_duration']:.1f} | {r['last_run']} |"
        for r in rows
    )
    return "\n".join(
        [
            f"# 📊 Agent Performance Dashboard — {current_date}",
            "",
            "> Generated by Morgan (Project Manager Agent)",
            "",
            f"**Time Period**: Last {period_days} days  ",
            f"**Sorted By**: `{sort_by}`",
            "",
            "| Agent | Runs | Success Rate | Failures | Avg Duration (min) | Last Run |",
            "|------|-----:|-------------:|---------:|-------------------:|---------|",
            kpi_lines,
            "",
            "---",
            "*KPIs are based on recent GitHub Actions workflow runs for each agent workflow.*",
            "*Note: metrics are computed from the most recent 100 workflow runs returned by the GitHub API.*",
            f"*🤖 Automated dashboard by Morgan (Project Manager Agent) · [Workflow run]({workflow_url})*",
        ]
    )


def main():
    parser = argparse.ArgumentParser(description="Generate agent performance dashboard markdown")
    parser.add_argument("--input", default="/tmp/agent-runs.json", help="Path to workflow runs JSON payload")
    args = parser.parse_args()

    now = datetime.now(timezone.utc)
    period_days = int(os.environ.get("PERIOD_DAYS", "30"))
    since = now - timedelta(days=period_days)
    sort_by = os.environ.get("SORT_BY", "success-rate")
    current_date = os.environ.get("CURRENT_DATE", now.strftime("%Y-%m-%d"))
    workflow_url = os.environ.get("WORKFLOW_URL", "")

    with open(args.input, "r", encoding="utf-8") as fh:
        payload = json.load(fh)

    runs = payload.get("workflow_runs", [])
    metrics = collect_metrics(runs, since, AGENT_WORKFLOWS)
    rows = sort_rows(build_rows(metrics), sort_by)
    print(render_markdown(rows, current_date, period_days, sort_by, workflow_url))


if __name__ == "__main__":
    main()
